markdown:   kramdown

url:    'https://danielclough.github.io'
baseurl: '/teadb'

plugins:
    - jekyll-admin
    - jekyll-language-plugin
    - jekyll-liquify

language_data: data.lang.%%
language_includes_dir: _i18n