markdown:   kramdown

certifications: 
- Organic
- Gluten Free
- B-Corp
- 1% for the Planet
- ISO 22000
- Fair Trade
- UTZ Certified
- Rainforest Alliance
- Non-GMO

url:    'https://danielclough.github.io'
baseurl: '/teadb'

plugins:
    - jekyll-admin
    - jekyll-language-plugin
    - jekyll-liquify

language_data: data.lang.%%
language_includes_dir: _i18n